// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "Modules/ModuleManager.h"
#include "UObject/ObjectMacros.h"
#include "httpClient/config.h"
#include "httpClient/pal.h"

// PlayFab Common includes
#include "XAsyncTaskQueueHelpers.h"
#include "Logging.h"
#include "XAsyncTaskManager.h"
#include "XAsyncTask.h"

// PlayFab Core includes
#include "PFAuthentication.h"
#include "PFAuthenticationAsyncTasks.h"
#include "PFAuthenticationTypeConverters.h"
#include "PFAuthenticationUnrealTypes.h"
#include "PFCore.h"
#include "PFCoreAsyncTasks.h"
#include "PFCoreTypes.h"
#include "PFEntity.h"
#include "PFEntityAsyncTasks.h"
#include "PFLocalUser.h"
#include "PFEntityTypes.h"
#include "PFEvents.h"
#include "PFEventsAsyncTasks.h"
#include "PFEventsTypeConverters.h"
#include "PFEventsUnrealTypes.h"
#include "PFEventPipeline.h"
#include "PFEventPipelineTypes.h"
#include "PFHttpConfig.h"
#include "PFHttpConfigTypes.h"
#include "PFPlatform.h"
#include "PFPlatformTypes.h"
#include "PFServiceConfig.h"
#include "PFServiceConfigTypes.h"
#include "PFTrace.h"
#include "PFCoreUnrealTypes.h"
#include "PFCoreTypeConverters.h"
#include "Xbox/PFAuthentication_Xbox.h"
#include "Xbox/PFAuthenticationAsyncTasks_Xbox.h"
#include "Xbox/PFAuthenticationTypes_Xbox.h"

// PlayFab Services includes
#include "PFServices.h"
#include "PFServicesAsyncTasks.h"
#include "PFServicesTypes.h"
#include "PFAccountManagement.h"
#include "PFAccountManagementAsyncTasks.h"
#include "PFAccountManagementUnrealTypes.h"
#include "PFCatalog.h"
#include "PFCatalogAsyncTasks.h"
#include "PFCatalogUnrealTypes.h"
#include "PFCloudScript.h"
#include "PFCloudScriptAsyncTasks.h"
#include "PFCloudScriptUnrealTypes.h"
#include "PFData.h"
#include "PFDataAsyncTasks.h"
#include "PFDataUnrealTypes.h"
#include "PFExperimentation.h"
#include "PFExperimentationAsyncTasks.h"
#include "PFExperimentationUnrealTypes.h"
#include "PFFriends.h"
#include "PFFriendsAsyncTasks.h"
#include "PFFriendsUnrealTypes.h"
#include "PFGroups.h"
#include "PFGroupsAsyncTasks.h"
#include "PFGroupsUnrealTypes.h"
#include "PFInventory.h"
#include "PFInventoryAsyncTasks.h"
#include "PFInventoryUnrealTypes.h"
#include "PFLeaderboards.h"
#include "PFLeaderboardsAsyncTasks.h"
#include "PFLeaderboardsUnrealTypes.h"
#include "PFLocalization.h"
#include "PFLocalizationAsyncTasks.h"
#include "PFLocalizationUnrealTypes.h"
#include "PFMultiplayerServer.h"
#include "PFMultiplayerServerAsyncTasks.h"
#include "PFMultiplayerServerUnrealTypes.h"
#include "PFPlatformSpecific.h"
#include "PFPlatformSpecificAsyncTasks.h"
#include "PFPlatformSpecificUnrealTypes.h"
#include "PFPlayerDataManagement.h"
#include "PFPlayerDataManagementAsyncTasks.h"
#include "PFPlayerDataManagementUnrealTypes.h"
#include "PFProfiles.h"
#include "PFProfilesAsyncTasks.h"
#include "PFProfilesUnrealTypes.h"
#include "PFPushNotifications.h"
#include "PFPushNotificationsAsyncTasks.h"
#include "PFPushNotificationsUnrealTypes.h"
#include "PFSegments.h"
#include "PFSegmentsAsyncTasks.h"
#include "PFSegmentsUnrealTypes.h"
#include "PFStatistics.h"
#include "PFStatisticsAsyncTasks.h"
#include "PFStatisticsUnrealTypes.h"
#include "PFTitleDataManagement.h"
#include "PFTitleDataManagementAsyncTasks.h"
#include "PFTitleDataManagementUnrealTypes.h"

// PlayFab GameSave includes
#include "PFGameSaveFiles.h"
#include "PFGameSaveFilesUi.h"

class PLAYFABUNREAL_API FPlayFabUnrealModule : public IModuleInterface
{
public:

	/** IModuleInterface implementation */
	virtual void StartupModule() override;
	virtual void ShutdownModule() override;
};